services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SECRET_KEY
      - DEBUG
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_data:/app/media
      - ./fixtures:/app/fixtures

  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  media_data:
  db_data: